# Generated by Django 4.2.7 on 2025-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_alter_lecturerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
