# Generated by Django 4.2.7 on 2025-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_alter_studentprofile_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='matric_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
