# Generated by Django 4.2.7 on 2025-06-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0007_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Department'), ('approved', 'Approved by Admin')], default='draft', max_length=20),
        ),
    ]
