# Generated by Django 4.2.7 on 2025-06-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0009_alter_customuser_position_hodprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('hod', 'Head of Department'), ('admin', 'Lecturer')], default='student', help_text="User's position in the institution", max_length=20),
        ),
    ]
