# Generated by Django 4.2.7 on 2025-06-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0011_remove_result_course_and_scores_grade_grade_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
