# Generated by Django 4.2.7 on 2025-06-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0012_alter_grade_grade_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
